### ISSUE TITLE
Unresolved Node Errors

### ISSUE THREAD

**Issue by stephensmitchell** [alvpickmans/JsonData#4]
This is the error in example JsonDataSample.

<img width="1226" alt="6-16-2019-7 16 20 PM" src="https://user-images.githubusercontent.com/5302428/59571544-8f349880-906b-11e9-9650-198914f0d038.png">

I believe this node was removed from the latest release. How do we make the examples work without these removed nodes or what new node replaces the missing ones?

Thank you.

Using Revit 2020 with the lastest udpdates.

<img width="562" alt="6-16-2019-7 19 54 PM" src="https://user-images.githubusercontent.com/5302428/59571565-bdb27380-906b-11e9-8a54-b1b69f9ac8a8.png">

Dynamo Version Info.

<img width="395" alt="6-16-2019-7 17 57 PM" src="https://user-images.githubusercontent.com/5302428/59571538-8348d680-906b-11e9-87ea-799584e7c5e2.png">

**Comment by alvpickmans** [comment]
Oh sure, this is my fault for not updating that file accordingly after making some breaking changes. Will solve it asap.

**Comment by stephensmitchell** [comment]
Hello @alvpickmans.

Can you explain how to fix the examples? How to handle JsonObject to JsonObject[] (JsonObjects)? Which node combination replaces the missing JsonArray.ByElements node? 
I understand you may not have time to work on this, I can If successful provide fixes.

Thank you.

**Comment by alvpickmans** [comment]
@stephensmitchell It seems that I did update the sample file on version 2.0.0, but for some reason it has been misplaced. I am working on updating the package (and repo) to have the proper files always shipped together. In the meantime please find the sample files on the zip below.

Basically, nodes are able to handle an array/list of `JsonObject` by themselves without relying on the old `JsonArray.ByElements`.

[JsonDataSample.zip](https://github.com/alvpickmans/JsonData/files/3349286/JsonDataSample.zip)

**Comment by stephensmitchell** [comment]
Thank you, it works and I now understand the new workflow much better.
